version: "3.3"
services:
  db:
    container_name: db_local
    image: mysql:8.0.32
    restart: always
    environment:
      MYSQL_DATABASE: 'hackathon'
      MYSQL_USER: 'mysql'
      MYSQL_PASSWORD: 'mysql'
      MYSQL_ROOT_PASSWORD: 'mysql'
      MYSQL_ROOT_HOST: '%'  # needs to be enclosed with quotes
    ports:
      - '3307:3306'
    expose:
      - '3307'
    volumes:
      - /var/lib/mysql:/var/lib/mysql
